plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

# Fixes for Vue's lack of Yarn 2 support 
packageExtensions:
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-babel": "^4.5.0"
      "@vue/cli-plugin-typescript": "^4.5.0"
      "vue-cli-plugin-vuetify": "^2.4.0"
  "@vue/cli-plugin-typescript@*":
    dependencies:
      "babel-loader": "^8.1.0"
      "@babel/core": "^7.11.0"
  "fork-ts-checker-webpack-plugin@*":
    dependencies:
      "vue-template-compiler": "*"
    peerDependencies:
      "typescript": "~3.9.3"
  "vue-router@*":
    dependencies:
      "vue": "^2.6.14"
  "vuex@*":
    dependencies:
      "vue": "^2.6.14"
  "@vue/component-compiler-utils@*":
    dependencies:
      "supports-color": "^8"
      "chalk": "*"
  "@babel/runtime@*":
    dependencies:
      "core-js": "^3.6.5"

